allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
  core-js: false
trustPolicyExclude:
  - chokidar@4.0.3
packages: ['.', 'crayon']
overrides:
  '@atcute/lexicons': 2.0.0
minimumReleaseAgeExclude:
  - usercss-parser@0.0.1
